apiVersion: v1
kind: Service
metadata:
  name: queue-service
spec:
  selector:
    app: queue
  ports:
    - name: admin-console
      port: 30010
      targetPort: 8161
      nodePort: 30010
  type: NodePort
